# Generated by Django 6.0.4 on 2026-05-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='complexidade',
            field=models.IntegerField(choices=[(1, 'Básico'), (2, 'Médio'), (3, 'Avançado')]),
        ),
    ]
