# Generated by Django 6.0.3 on 2026-05-11 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0002_alter_processo_complexidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='juiz',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Status Ativo'),
        ),
        migrations.AddField(
            model_name='juiz',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='juiz_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('juiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessor', to='sorteio.juiz')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssistenteJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistente_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
