# Generated by Django 6.0.3 on 2026-05-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0003_juiz_ativo_juiz_user_assessor_assistentejuridico'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('Aguardando Sorteio', 'Aguardando Sorteio'), ('Sorteado', 'Sorteado')], default='Aguardando Sorteio', max_length=30),
        ),
        migrations.AlterField(
            model_name='processo',
            name='complexidade',
            field=models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermediário'), (3, 'Complexo')]),
        ),
    ]
